# Inspect NLG Inputs

This notebook loads the existing result artifacts and shows the exact sample objects that feed the NLG agent.

It supports both:
- `results/final_report2025_us`
- `results/final_report2025_eu`

You can inspect:
- the monthly sample catalog
- the prompt context sent to the NLG pipeline
- the flattened facts/triples
- the per-stock recommendation, target price, justification, and indicator table
- the raw selected sample as JSON

In [1]:
from pathlib import Path
import json
import sys

import pandas as pd
from IPython.display import JSON, Markdown, display

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "load_data.py").exists():
    fallback = Path("/home/chinonso/PHD_PROJECTS/Financial-D2T-Agent")
    if fallback.exists():
        PROJECT_ROOT = fallback

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from load_data import load_generation_samples

PROJECT_ROOT

PosixPath('/home/chinonso/PHD_PROJECTS/Financial-D2T-Agent')

In [2]:
REGION = "us"  # change to "eu" if needed
DATASET_PATH = PROJECT_ROOT / "results" / f"final_report2025_{REGION}"
DATASET_KIND = "auto"
START_DATE = None
END_DATE = None
TICKERS = None  # example: ["AAPL", "TSLA"]
MIN_STOCKS_PER_MONTH = 1

print("Dataset path:", DATASET_PATH)
print("Exists:", DATASET_PATH.exists())

Dataset path: /home/chinonso/PHD_PROJECTS/Financial-D2T-Agent/results/final_report2025_us
Exists: True

In [11]:
table1_us_summary = pd.read_csv("results/validation/us/table1_us_summary.csv")
table1_us_summary

,model,architecture,reflection,n_analyses,n_runs,n_buy,n_hold,n_sell,mean_nmae,mean_penalty_rate,mean_score_one,mean_score,mean_cum_return,mean_sharpe_12m,n_tickers_traded,mean_tokens_per_analysis,mean_total_tokens
0,gpt-5,workflow,False,112,1,32,29,51,0.113556,0.177083,1.884389,1.884389,0.083007,0.466795,8,98377.116071,98377.116071
1,gpt-5,workflow,True,112,1,26,32,54,0.102843,0.135417,1.457010,1.457010,0.128123,0.358632,8,164408.089286,164408.089286
2,gpt-5-mini,workflow,False,112,1,30,29,53,0.105917,0.107887,1.184786,1.184786,0.010337,-0.045864,8,83029.526786,83029.526786
3,gpt-5-mini,workflow,True,112,1,27,28,57,0.097922,0.052827,0.626196,0.626196,0.013080,0.130558,8,127942.526786,127942.526786

In [12]:
table2_us_rows_gpt_5_workflow_false = pd.read_csv("results/validation/us/table2_us_rows_gpt-5_workflow_false.csv")
table2_us_rows_gpt_5_workflow_false

,ticker,analysis_date,run_id,indicator,predicted,gold,source,gold_date,capture_date,units,...,strategy_return,cum_return,sharpe_12m,pnl_available,normalised_error,abs_pct_error,normalisation_method,ratio_clip_applied,gold_min_for_scaling,gold_max_for_scaling
0,AAPL,2026-02-25,0,BVPS,5.954617e+00,5.310000e+00,gold,2026-02-25,2026-02-25,USD_per_share,...,0.0,0.0,0.0,1,0.005952,1.213968e-01,minmax_gold,0,-5.910000e+01,4.921000e+01
1,AAPL,2026-02-25,0,CashAndEquivalents,4.531700e+10,5.470000e+10,gold,2026-02-25,2026-02-25,USD,...,0.0,0.0,0.0,1,0.082329,1.715356e-01,minmax_gold,0,9.060000e+09,1.230300e+11
2,AAPL,2026-02-25,0,CurrentRatio,9.737447e-01,8.900000e-01,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.0,0.0,1,0.053682,9.409513e-02,minmax_gold,0,8.400000e-01,2.400000e+00
3,AAPL,2026-02-25,0,EBITMargin,3.197080e+01,3.197000e+01,gold,2026-02-25,2026-02-25,percent,...,0.0,0.0,0.0,1,0.000010,2.501603e-05,minmax_gold,0,-3.255000e+01,4.627000e+01
4,AAPL,2026-02-25,0,EBIT_TTM,1.330500e+11,1.330500e+11,gold,2026-02-25,2026-02-25,USD,...,0.0,0.0,0.0,1,0.000000,1.146846e-16,minmax_gold,0,-2.260000e+10,1.359400e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,TSLA,2026-02-25,0,P_E,3.881358e+02,2.718500e+02,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.0,0.0,1,0.468857,4.277572e-01,minmax_gold,0,2.383000e+01,2.718500e+02
159,TSLA,2026-02-25,0,PriceToSales,1.552920e+01,1.498000e+01,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.0,0.0,1,0.038594,3.666204e-02,minmax_gold,0,7.500000e-01,1.498000e+01
160,TSLA,2026-02-25,0,ROE,4.578531e+00,1.488000e+01,gold,2026-02-25,2026-02-25,percent,...,0.0,0.0,0.0,1,0.072900,6.923030e-01,minmax_gold,0,1.488000e+01,1.561900e+02
161,TSLA,2026-02-25,0,ROIC,4.784768e+00,4.190000e+00,gold,2026-02-25,2026-02-25,percent,...,0.0,0.0,0.0,1,0.010697,1.419494e-01,minmax_gold,0,4.190000e+00,5.979000e+01
162,TSLA,2026-02-25,0,ShareholdersEquity,8.286500e+10,3.817000e+10,gold,2026-02-25,2026-02-25,USD,...,0.0,0.0,0.0,1,0.087003,1.170946e+00,minmax_gold,0,-1.248000e+11,3.889200e+11

In [13]:
table2_us_rows_gpt_5_workflow_true = pd.read_csv("results/validation/us/table2_us_rows_gpt-5_workflow_true.csv")
table2_us_rows_gpt_5_workflow_true

,ticker,analysis_date,run_id,indicator,predicted,gold,source,gold_date,capture_date,units,...,strategy_return,cum_return,sharpe_12m,pnl_available,normalised_error,abs_pct_error,normalisation_method,ratio_clip_applied,gold_min_for_scaling,gold_max_for_scaling
0,AAPL,2026-02-25,0,BVPS,5.954617e+00,5.310000e+00,gold,2026-02-25,2026-02-25,USD_per_share,...,0.0,0.241619,0.780125,1,0.005952,1.213968e-01,minmax_gold,0,-5.910000e+01,4.921000e+01
1,AAPL,2026-02-25,0,CashAndEquivalents,4.531700e+10,5.470000e+10,gold,2026-02-25,2026-02-25,USD,...,0.0,0.241619,0.780125,1,0.082329,1.715356e-01,minmax_gold,0,9.060000e+09,1.230300e+11
2,AAPL,2026-02-25,0,CurrentRatio,9.737447e-01,8.900000e-01,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.241619,0.780125,1,0.053682,9.409513e-02,minmax_gold,0,8.400000e-01,2.400000e+00
3,AAPL,2026-02-25,0,EBITMargin,3.197080e+01,3.197000e+01,gold,2026-02-25,2026-02-25,percent,...,0.0,0.241619,0.780125,1,0.000010,2.501603e-05,minmax_gold,0,-3.255000e+01,4.627000e+01
4,AAPL,2026-02-25,0,EBIT_TTM,1.330500e+11,1.330500e+11,gold,2026-02-25,2026-02-25,USD,...,0.0,0.241619,0.780125,1,0.000000,1.146846e-16,minmax_gold,0,-2.260000e+10,1.359400e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,TSLA,2026-02-25,0,P_E,3.881358e+02,2.718500e+02,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.000000,0.000000,1,0.468857,4.277572e-01,minmax_gold,0,2.383000e+01,2.718500e+02
159,TSLA,2026-02-25,0,PriceToSales,1.552920e+01,1.498000e+01,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.000000,0.000000,1,0.038594,3.666204e-02,minmax_gold,0,7.500000e-01,1.498000e+01
160,TSLA,2026-02-25,0,ROE,4.619112e+00,1.488000e+01,gold,2026-02-25,2026-02-25,percent,...,0.0,0.000000,0.000000,1,0.072613,6.895758e-01,minmax_gold,0,1.488000e+01,1.561900e+02
161,TSLA,2026-02-25,0,ROIC,4.823347e+00,4.190000e+00,gold,2026-02-25,2026-02-25,percent,...,0.0,0.000000,0.000000,1,0.011391,1.511568e-01,minmax_gold,0,4.190000e+00,5.979000e+01
162,TSLA,2026-02-25,0,ShareholdersEquity,8.213700e+10,3.817000e+10,gold,2026-02-25,2026-02-25,USD,...,0.0,0.000000,0.000000,1,0.085586,1.151873e+00,minmax_gold,0,-1.248000e+11,3.889200e+11

In [14]:
table2_us_rows_gpt_5_mini_workflow_false = pd.read_csv("results/validation/us/table2_us_rows_gpt-5-mini_workflow_false.csv")
table2_us_rows_gpt_5_mini_workflow_false

,ticker,analysis_date,run_id,indicator,predicted,gold,source,gold_date,capture_date,units,...,strategy_return,cum_return,sharpe_12m,pnl_available,normalised_error,abs_pct_error,normalisation_method,ratio_clip_applied,gold_min_for_scaling,gold_max_for_scaling
0,AAPL,2026-02-25,0,BVPS,5.954617e+00,5.310000e+00,gold,2026-02-25,2026-02-25,USD_per_share,...,0.0,0.0,0.0,1,0.005952,1.213968e-01,minmax_gold,0,-5.910000e+01,4.921000e+01
1,AAPL,2026-02-25,0,CashAndEquivalents,4.531700e+10,5.470000e+10,gold,2026-02-25,2026-02-25,USD,...,0.0,0.0,0.0,1,0.082329,1.715356e-01,minmax_gold,0,9.060000e+09,1.230300e+11
2,AAPL,2026-02-25,0,CurrentRatio,9.737447e-01,8.900000e-01,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.0,0.0,1,0.053682,9.409513e-02,minmax_gold,0,8.400000e-01,2.400000e+00
3,AAPL,2026-02-25,0,EBITMargin,3.197080e+01,3.197000e+01,gold,2026-02-25,2026-02-25,percent,...,0.0,0.0,0.0,1,0.000010,2.501603e-05,minmax_gold,0,-3.255000e+01,4.627000e+01
4,AAPL,2026-02-25,0,EBIT_TTM,1.330500e+11,1.330500e+11,gold,2026-02-25,2026-02-25,USD,...,0.0,0.0,0.0,1,0.000000,1.146846e-16,minmax_gold,0,-2.260000e+10,1.359400e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,TSLA,2026-02-25,0,P_E,3.881358e+02,2.718500e+02,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.0,0.0,1,0.468857,4.277572e-01,minmax_gold,0,2.383000e+01,2.718500e+02
159,TSLA,2026-02-25,0,PriceToSales,1.552920e+01,1.498000e+01,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.0,0.0,1,0.038594,3.666204e-02,minmax_gold,0,7.500000e-01,1.498000e+01
160,TSLA,2026-02-25,0,ROE,4.578531e+00,1.488000e+01,gold,2026-02-25,2026-02-25,percent,...,0.0,0.0,0.0,1,0.072900,6.923030e-01,minmax_gold,0,1.488000e+01,1.561900e+02
161,TSLA,2026-02-25,0,ROIC,4.784768e+00,4.190000e+00,gold,2026-02-25,2026-02-25,percent,...,0.0,0.0,0.0,1,0.010697,1.419494e-01,minmax_gold,0,4.190000e+00,5.979000e+01
162,TSLA,2026-02-25,0,ShareholdersEquity,8.286500e+10,3.817000e+10,gold,2026-02-25,2026-02-25,USD,...,0.0,0.0,0.0,1,0.087003,1.170946e+00,minmax_gold,0,-1.248000e+11,3.889200e+11

In [15]:
table2_us_rows_gpt_5_mini_workflow_true = pd.read_csv("results/validation/us/table2_us_rows_gpt-5-mini_workflow_true.csv")
table2_us_rows_gpt_5_mini_workflow_true

,ticker,analysis_date,run_id,indicator,predicted,gold,source,gold_date,capture_date,units,...,strategy_return,cum_return,sharpe_12m,pnl_available,normalised_error,abs_pct_error,normalisation_method,ratio_clip_applied,gold_min_for_scaling,gold_max_for_scaling
0,AAPL,2026-02-25,0,BVPS,5.954617e+00,5.310000e+00,gold,2026-02-25,2026-02-25,USD_per_share,...,0.0,0.0,0.0,1,0.005952,1.213968e-01,minmax_gold,0,-5.910000e+01,4.921000e+01
1,AAPL,2026-02-25,0,CashAndEquivalents,4.531700e+10,5.470000e+10,gold,2026-02-25,2026-02-25,USD,...,0.0,0.0,0.0,1,0.082329,1.715356e-01,minmax_gold,0,9.060000e+09,1.230300e+11
2,AAPL,2026-02-25,0,CurrentRatio,9.737447e-01,8.900000e-01,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.0,0.0,1,0.053682,9.409513e-02,minmax_gold,0,8.400000e-01,2.400000e+00
3,AAPL,2026-02-25,0,EBITMargin,3.197080e+01,3.197000e+01,gold,2026-02-25,2026-02-25,percent,...,0.0,0.0,0.0,1,0.000010,2.501603e-05,minmax_gold,0,-3.255000e+01,4.627000e+01
4,AAPL,2026-02-25,0,EBIT_TTM,1.330500e+11,1.330500e+11,gold,2026-02-25,2026-02-25,USD,...,0.0,0.0,0.0,1,0.000000,1.146846e-16,minmax_gold,0,-2.260000e+10,1.359400e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,TSLA,2026-02-25,0,P_E,3.881358e+02,2.718500e+02,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.0,0.0,1,0.468857,4.277572e-01,minmax_gold,0,2.383000e+01,2.718500e+02
159,TSLA,2026-02-25,0,PriceToSales,1.552920e+01,1.498000e+01,gold,2026-02-25,2026-02-25,multiple,...,0.0,0.0,0.0,1,0.038594,3.666204e-02,minmax_gold,0,7.500000e-01,1.498000e+01
160,TSLA,2026-02-25,0,ROE,4.578531e+00,1.488000e+01,gold,2026-02-25,2026-02-25,percent,...,0.0,0.0,0.0,1,0.072900,6.923030e-01,minmax_gold,0,1.488000e+01,1.561900e+02
161,TSLA,2026-02-25,0,ROIC,4.784768e+00,4.190000e+00,gold,2026-02-25,2026-02-25,percent,...,0.0,0.0,0.0,1,0.010697,1.419494e-01,minmax_gold,0,4.190000e+00,5.979000e+01
162,TSLA,2026-02-25,0,ShareholdersEquity,8.286500e+10,3.817000e+10,gold,2026-02-25,2026-02-25,USD,...,0.0,0.0,0.0,1,0.087003,1.170946e+00,minmax_gold,0,-1.248000e+11,3.889200e+11

In [16]:
table2_us_summary_gpt_5_workflow_false = pd.read_csv("results/validation/us/table2_us_summary_gpt-5_workflow_false.csv")
table2_us_summary_gpt_5_workflow_false

,indicator,n_points,n_rows,n_tickers,n_analysis_dates,mean_normalised_error,median_normalised_error,nmae,median_ape,penalty_rate,score_one,alpha,capture_dates_unique_count,capture_date_min,capture_date_max,notes
0,EBITMargin,8,8,8,1,0.015979,0.003544,0.015979,0.006781,0.000000,0.015979,10.0,1,2026-02-25,2026-02-25,NaN
1,NetRevenue_TTM,8,8,8,1,0.015988,0.000911,0.015988,0.024012,0.000000,0.015988,10.0,1,2026-02-25,2026-02-25,NaN
2,EBIT_TTM,8,8,8,1,0.025577,0.003941,0.025577,0.044328,0.000000,0.025577,10.0,1,2026-02-25,2026-02-25,NaN
3,EV_EBIT,7,7,7,1,0.038504,0.011068,0.038504,0.096904,0.000000,0.038504,10.0,1,2026-02-25,2026-02-25,NaN
4,NetProfit_TTM,8,8,8,1,0.039475,0.011563,0.039475,0.100273,0.000000,0.039475,10.0,1,2026-02-25,2026-02-25,NaN
5,CurrentRatio,8,8,8,1,0.041065,0.022699,0.041065,0.016834,0.000000,0.041065,10.0,1,2026-02-25,2026-02-25,NaN
6,NetMargin,8,8,8,1,0.049337,0.007276,0.049337,0.016708,0.000000,0.049337,10.0,1,2026-02-25,2026-02-25,NaN
7,NetDebt,8,8,8,1,0.080997,0.036427,0.080997,0.253863,0.000000,0.080997,10.0,1,2026-02-25,2026-02-25,NaN
8,ROIC,7,7,7,1,0.082598,0.062574,0.082598,0.161427,0.000000,0.082598,10.0,1,2026-02-25,2026-02-25,NaN
9,GrossDebt_Equity,8,8,8,1,0.084403,0.014827,0.084403,0.369772,0.000000,0.084403,10.0,1,2026-02-25,2026-02-25,NaN
10,P_E,7,7,7,1,0.090029,0.020706,0.090029,0.215501,0.000000,0.090029,10.0,1,2026-02-25,2026-02-25,NaN
11,EPS,8,8,8,1,0.099259,0.021900,0.099259,0.101940,0.000000,0.099259,10.0,1,2026-02-25,2026-02-25,NaN
12,ShareholdersEquity,8,8,8,1,0.102673,0.050008,0.102673,0.551534,0.000000,0.102673,10.0,1,2026-02-25,2026-02-25,NaN
13,PriceToSales,8,8,8,1,0.103797,0.051953,0.103797,0.167997,0.000000,0.103797,10.0,1,2026-02-25,2026-02-25,NaN
14,EV_EBITDA,7,7,7,1,0.108069,0.114596,0.108069,0.191928,0.285714,2.965212,10.0,1,2026-02-25,2026-02-25,NaN
15,ROE,7,7,7,1,0.131925,0.113571,0.131925,0.484734,0.000000,0.131925,10.0,1,2026-02-25,2026-02-25,NaN
16,GrossDebt,8,8,8,1,0.139302,0.080820,0.139302,0.371973,0.000000,0.139302,10.0,1,2026-02-25,2026-02-25,NaN
17,BVPS,8,8,8,1,0.140241,0.079266,0.140241,0.544372,0.000000,0.140241,10.0,1,2026-02-25,2026-02-25,NaN
18,P_B,8,8,8,1,0.148282,0.100364,0.148282,0.480407,0.000000,0.148282,10.0,1,2026-02-25,2026-02-25,NaN
19,GrossMargin,8,8,8,1,0.149084,0.004486,0.149084,0.005339,0.125000,1.399084,10.0,1,2026-02-25,2026-02-25,NaN
20,CashAndEquivalents,8,8,8,1,0.257879,0.184015,0.257879,0.448965,0.000000,0.257879,10.0,1,2026-02-25,2026-02-25,NaN

In [17]:
table2_us_summary_gpt_5_workflow_true = pd.read_csv("results/validation/us/table2_us_summary_gpt-5_workflow_true.csv")
table2_us_summary_gpt_5_workflow_true

,indicator,n_points,n_rows,n_tickers,n_analysis_dates,mean_normalised_error,median_normalised_error,nmae,median_ape,penalty_rate,score_one,alpha,capture_dates_unique_count,capture_date_min,capture_date_max,notes
0,CurrentRatio,8,8,8,1,0.040999,0.022699,0.040999,0.016834,0.000000,0.040999,10.0,1,2026-02-25,2026-02-25,NaN
1,EV_EBIT,7,7,7,1,0.051825,0.024357,0.051825,0.164914,0.142857,1.480396,10.0,1,2026-02-25,2026-02-25,NaN
2,NetRevenue_TTM,8,8,8,1,0.065717,0.000911,0.065717,0.026711,0.125000,1.315717,10.0,1,2026-02-25,2026-02-25,NaN
3,EBITMargin,8,8,8,1,0.084915,0.004154,0.084915,0.013625,0.125000,1.334915,10.0,1,2026-02-25,2026-02-25,NaN
4,NetDebt,8,8,8,1,0.089031,0.063911,0.089031,0.402650,0.000000,0.089031,10.0,1,2026-02-25,2026-02-25,NaN
5,EV_EBITDA,7,7,7,1,0.095825,0.062779,0.095825,0.209777,0.142857,1.524396,10.0,1,2026-02-25,2026-02-25,NaN
6,NetMargin,8,8,8,1,0.101916,0.007276,0.101916,0.016708,0.125000,1.351916,10.0,1,2026-02-25,2026-02-25,NaN
7,ShareholdersEquity,8,8,8,1,0.102230,0.050008,0.102230,0.551534,0.000000,0.102230,10.0,1,2026-02-25,2026-02-25,NaN
8,P_E,7,7,7,1,0.104464,0.020706,0.104464,0.215501,0.142857,1.533035,10.0,1,2026-02-25,2026-02-25,NaN
9,NetProfit_TTM,8,8,8,1,0.115671,0.011563,0.115671,0.171909,0.125000,1.365671,10.0,1,2026-02-25,2026-02-25,NaN
10,EBIT_TTM,8,8,8,1,0.127403,0.003398,0.127403,0.072858,0.125000,1.377403,10.0,1,2026-02-25,2026-02-25,NaN
11,GrossDebt,8,8,8,1,0.133724,0.077270,0.133724,0.322890,0.000000,0.133724,10.0,1,2026-02-25,2026-02-25,NaN
12,BVPS,8,8,8,1,0.139373,0.078314,0.139373,0.543952,0.000000,0.139373,10.0,1,2026-02-25,2026-02-25,NaN
13,ROIC,7,7,7,1,0.142143,0.062590,0.142143,0.245272,0.142857,1.570714,10.0,1,2026-02-25,2026-02-25,NaN
14,P_B,8,8,8,1,0.147863,0.100344,0.147863,0.478207,0.000000,0.147863,10.0,1,2026-02-25,2026-02-25,NaN
15,EPS,8,8,8,1,0.158998,0.021900,0.158998,0.177326,0.125000,1.408998,10.0,1,2026-02-25,2026-02-25,NaN
16,ROE,7,7,7,1,0.162735,0.125823,0.162735,0.636600,0.142857,1.591306,10.0,1,2026-02-25,2026-02-25,NaN
17,GrossMargin,8,8,8,1,0.187333,0.006891,0.187333,0.023643,0.125000,1.437333,10.0,1,2026-02-25,2026-02-25,NaN
18,PriceToSales,8,8,8,1,0.189749,0.051953,0.189749,0.167997,0.125000,1.439749,10.0,1,2026-02-25,2026-02-25,NaN
19,CashAndEquivalents,8,8,8,1,0.257879,0.184015,0.257879,0.448965,0.000000,0.257879,10.0,1,2026-02-25,2026-02-25,NaN
20,GrossDebt_Equity,8,8,8,1,0.493381,0.014060,0.493381,0.316688,0.000000,0.493381,10.0,1,2026-02-25,2026-02-25,NaN

In [18]:
table2_us_summary_gpt_5_mini_workflow_false = pd.read_csv("results/validation/us/table2_us_summary_gpt-5-mini_workflow_false.csv")
table2_us_summary_gpt_5_mini_workflow_false

,indicator,n_points,n_rows,n_tickers,n_analysis_dates,mean_normalised_error,median_normalised_error,nmae,median_ape,penalty_rate,score_one,alpha,capture_dates_unique_count,capture_date_min,capture_date_max,notes
0,NetRevenue_TTM,8,8,8,1,0.039291,0.000911,0.039291,0.026711,0.125,1.289291,10.0,1,2026-02-25,2026-02-25,NaN
1,CurrentRatio,8,8,8,1,0.041065,0.022699,0.041065,0.016834,0.000,0.041065,10.0,1,2026-02-25,2026-02-25,NaN
2,EV_EBIT,7,7,7,1,0.042186,0.019887,0.042186,0.142314,0.000,0.042186,10.0,1,2026-02-25,2026-02-25,NaN
3,NetProfit_TTM,8,8,8,1,0.061144,0.011506,0.061144,0.171909,0.000,0.061144,10.0,1,2026-02-25,2026-02-25,NaN
4,EBITMargin,8,8,8,1,0.068495,0.004154,0.068495,0.020744,0.125,1.318495,10.0,1,2026-02-25,2026-02-25,NaN
5,EBIT_TTM,8,8,8,1,0.069794,0.003941,0.069794,0.072858,0.125,1.319794,10.0,1,2026-02-25,2026-02-25,NaN
6,EV_EBITDA,7,7,7,1,0.080906,0.056667,0.080906,0.206914,0.000,0.080906,10.0,1,2026-02-25,2026-02-25,NaN
7,GrossDebt_Equity,8,8,8,1,0.083954,0.014155,0.083954,0.316688,0.000,0.083954,10.0,1,2026-02-25,2026-02-25,NaN
8,P_E,7,7,7,1,0.087874,0.020706,0.087874,0.215501,0.000,0.087874,10.0,1,2026-02-25,2026-02-25,NaN
9,NetDebt,8,8,8,1,0.089049,0.063911,0.089049,0.402746,0.000,0.089049,10.0,1,2026-02-25,2026-02-25,NaN
10,ROIC,7,7,7,1,0.099208,0.062574,0.099208,0.245356,0.000,0.099208,10.0,1,2026-02-25,2026-02-25,NaN
11,ShareholdersEquity,8,8,8,1,0.102673,0.050008,0.102673,0.551534,0.000,0.102673,10.0,1,2026-02-25,2026-02-25,NaN
12,NetMargin,8,8,8,1,0.109176,0.013571,0.109176,0.092201,0.125,1.359176,10.0,1,2026-02-25,2026-02-25,NaN
13,EPS,8,8,8,1,0.118262,0.021900,0.118262,0.177326,0.000,0.118262,10.0,1,2026-02-25,2026-02-25,NaN
14,PriceToSales,8,8,8,1,0.130654,0.056897,0.130654,0.167997,0.125,1.380654,10.0,1,2026-02-25,2026-02-25,NaN
15,GrossDebt,8,8,8,1,0.133734,0.077311,0.133734,0.322890,0.000,0.133734,10.0,1,2026-02-25,2026-02-25,NaN
16,BVPS,8,8,8,1,0.140217,0.079266,0.140217,0.544372,0.000,0.140217,10.0,1,2026-02-25,2026-02-25,NaN
17,ROE,7,7,7,1,0.145532,0.113571,0.145532,0.484734,0.000,0.145532,10.0,1,2026-02-25,2026-02-25,NaN
18,P_B,8,8,8,1,0.148986,0.100364,0.148986,0.480407,0.000,0.148986,10.0,1,2026-02-25,2026-02-25,NaN
19,GrossMargin,8,8,8,1,0.168429,0.005552,0.168429,0.005751,0.250,2.668429,10.0,1,2026-02-25,2026-02-25,NaN
20,CashAndEquivalents,8,8,8,1,0.257879,0.184015,0.257879,0.448965,0.000,0.257879,10.0,1,2026-02-25,2026-02-25,NaN

In [19]:
table2_us_summary_gpt_5_mini_workflow_true = pd.read_csv("results/validation/us/table2_us_summary_gpt-5-mini_workflow_true.csv")
table2_us_summary_gpt_5_mini_workflow_true

,indicator,n_points,n_rows,n_tickers,n_analysis_dates,mean_normalised_error,median_normalised_error,nmae,median_ape,penalty_rate,score_one,alpha,capture_dates_unique_count,capture_date_min,capture_date_max,notes
0,EBITMargin,8,8,8,1,0.018028,0.004154,0.018028,0.013625,0.0,0.018028,10.0,1,2026-02-25,2026-02-25,NaN
1,NetRevenue_TTM,8,8,8,1,0.037704,0.000911,0.037704,0.026711,0.0,0.037704,10.0,1,2026-02-25,2026-02-25,NaN
2,CurrentRatio,8,8,8,1,0.041266,0.022699,0.041266,0.016834,0.0,0.041266,10.0,1,2026-02-25,2026-02-25,NaN
3,EV_EBIT,7,7,7,1,0.041355,0.013915,0.041355,0.121829,0.0,0.041355,10.0,1,2026-02-25,2026-02-25,NaN
4,NetMargin,8,8,8,1,0.053573,0.007276,0.053573,0.016708,0.0,0.053573,10.0,1,2026-02-25,2026-02-25,NaN
5,GrossMargin,8,8,8,1,0.053891,0.004929,0.053891,0.005751,0.0,0.053891,10.0,1,2026-02-25,2026-02-25,NaN
6,NetProfit_TTM,8,8,8,1,0.059965,0.011563,0.059965,0.171909,0.0,0.059965,10.0,1,2026-02-25,2026-02-25,NaN
7,EBIT_TTM,8,8,8,1,0.067431,0.003941,0.067431,0.072858,0.0,0.067431,10.0,1,2026-02-25,2026-02-25,NaN
8,EV_EBITDA,7,7,7,1,0.077477,0.046943,0.077477,0.206914,0.0,0.077477,10.0,1,2026-02-25,2026-02-25,NaN
9,P_E,7,7,7,1,0.088195,0.020706,0.088195,0.215501,0.0,0.088195,10.0,1,2026-02-25,2026-02-25,NaN
10,NetDebt,8,8,8,1,0.091180,0.060110,0.091180,0.364166,0.0,0.091180,10.0,1,2026-02-25,2026-02-25,NaN
11,ROIC,7,7,7,1,0.098705,0.062574,0.098705,0.245356,0.0,0.098705,10.0,1,2026-02-25,2026-02-25,NaN
12,ShareholdersEquity,8,8,8,1,0.104058,0.050008,0.104058,0.551534,0.0,0.104058,10.0,1,2026-02-25,2026-02-25,NaN
13,EPS,8,8,8,1,0.114954,0.021900,0.114954,0.177326,0.0,0.114954,10.0,1,2026-02-25,2026-02-25,NaN
14,P_B,8,8,8,1,0.120306,0.073661,0.120306,0.480407,0.0,0.120306,10.0,1,2026-02-25,2026-02-25,NaN
15,PriceToSales,8,8,8,1,0.127192,0.059780,0.127192,0.180625,0.0,0.127192,10.0,1,2026-02-25,2026-02-25,NaN
16,GrossDebt,8,8,8,1,0.136863,0.081115,0.136863,0.332038,0.0,0.136863,10.0,1,2026-02-25,2026-02-25,NaN
17,GrossDebt_Equity,8,8,8,1,0.138503,0.014155,0.138503,0.360270,0.0,0.138503,10.0,1,2026-02-25,2026-02-25,NaN
18,BVPS,8,8,8,1,0.143440,0.079266,0.143440,0.544372,0.0,0.143440,10.0,1,2026-02-25,2026-02-25,NaN
19,ROE,7,7,7,1,0.145648,0.113571,0.145648,0.484734,0.0,0.145648,10.0,1,2026-02-25,2026-02-25,NaN
20,CashAndEquivalents,8,8,8,1,0.257879,0.184015,0.257879,0.448965,0.0,0.257879,10.0,1,2026-02-25,2026-02-25,NaN

In [3]:
samples = load_generation_samples(
    dataset_path=str(DATASET_PATH),
    dataset_kind=DATASET_KIND,
    start_date=START_DATE,
    end_date=END_DATE,
    tickers=TICKERS,
    min_stocks_per_month=MIN_STOCKS_PER_MONTH,
)

print(f"Loaded {len(samples)} samples.")

Loaded 14 samples.

In [4]:
catalog = pd.DataFrame(
    [
        {
            "sample_id": sample["sample_id"],
            "sample_name": sample.get("sample_name"),
            "analysis_date": sample.get("analysis_date"),
            "ticker_count": sample.get("ticker_count"),
            "tickers": ", ".join(sample.get("tickers", [])),
            "previous_analysis_date": sample.get("previous_analysis_date"),
        }
        for sample in samples
    ]
)

catalog

,sample_id,sample_name,analysis_date,ticker_count,tickers,previous_analysis_date
0,1,multi_stock_2025-01-31,2025-01-31,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",None
1,2,multi_stock_2025-02-28,2025-02-28,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-01-31
2,3,multi_stock_2025-03-31,2025-03-31,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-02-28
3,4,multi_stock_2025-04-30,2025-04-30,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-03-31
4,5,multi_stock_2025-05-31,2025-05-31,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-04-30
5,6,multi_stock_2025-06-30,2025-06-30,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-05-31
6,7,multi_stock_2025-07-31,2025-07-31,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-06-30
7,8,multi_stock_2025-08-31,2025-08-31,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-07-31
8,9,multi_stock_2025-09-30,2025-09-30,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-08-31
9,10,multi_stock_2025-10-31,2025-10-31,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-09-30
10,11,multi_stock_2025-11-30,2025-11-30,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-10-31
11,12,multi_stock_2025-12-31,2025-12-31,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-11-30
12,13,multi_stock_2026-01-31,2026-01-31,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2025-12-31
13,14,multi_stock_2026-02-25,2026-02-25,8,"AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA",2026-01-31

In [5]:
SELECTED_SAMPLE_ID = 1
SELECTED_ANALYSIS_DATE = None  # example: "2025-03-31"


def get_sample(sample_list, sample_id=None, analysis_date=None):
    if analysis_date:
        for sample in sample_list:
            if str(sample.get("analysis_date", ""))[:10] == analysis_date:
                return sample
        raise KeyError(f"No sample found for analysis_date={analysis_date!r}")

    for sample in sample_list:
        if int(sample["sample_id"]) == int(sample_id):
            return sample
    raise KeyError(f"No sample found for sample_id={sample_id!r}")


sample = get_sample(
    samples,
    sample_id=SELECTED_SAMPLE_ID,
    analysis_date=SELECTED_ANALYSIS_DATE,
)

sample["sample_name"], sample["analysis_date"], sample.get("tickers")

('multi_stock_2025-01-31',
 '2025-01-31',
 ['AAPL', 'AMZN', 'COIN', 'GOOG', 'MSFT', 'NFLX', 'NIO', 'TSLA'])

In [6]:
sample_summary = {
    "sample_id": sample.get("sample_id"),
    "sample_name": sample.get("sample_name"),
    "sample_type": sample.get("sample_type"),
    "analysis_date": sample.get("analysis_date"),
    "tickers": sample.get("tickers"),
    "ticker_count": sample.get("ticker_count"),
    "previous_analysis_date": sample.get("previous_analysis_date"),
    "previous_report_preview": str(sample.get("previous_report", "N/A"))[:300],
}

pd.Series(sample_summary)

sample_id                                                                1
sample_name                                         multi_stock_2025-01-31
sample_type                                            multi_stock_monthly
analysis_date                                                   2025-01-31
tickers                    [AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA]
ticker_count                                                             8
previous_analysis_date                                                None
previous_report_preview                                                N/A
dtype: object

In [7]:
display(Markdown("## Prompt Context Sent To The NLG Agent"))
print(sample["prompt_context"])

## Prompt Context Sent To The NLG Agent

Analysis month: 2025-01-31
Tickers in bundle (8): AAPL, AMZN, COIN, GOOG, MSFT, NFLX, NIO, TSLA
Previous month's multi-stock report context:
N/A

Current month structured bundle:
- AAPL: recommendation=Hold, target_price=236
  - recommendation_justification: I recommend Hold. The decisive indicators are elevated valuation (P/E 38.15; EV/EBIT 29.35) balanced against strong profitability (TTM EBIT $123.216B and net margin 23.97%) and exceptional capital efficiency (ROIC 75.34%). P/E and EV/EBIT valuations converge near the current market price (P/E-implied $236 and EV/EBIT-implied ~$234.8), so the target is set at $236 reflecting limited near‑term upside absent a meaningful re-rating or sustained acceleration in revenue or margins.
  - (AAPL, AssetTurnover, 1.136449)
  - (AAPL, Assets, 344085000000)
  - (AAPL, BVPS, 4.406217)
  - (AAPL, CashAndEquivalents, 30299000000)
  - (AAPL, CurrentAssets, 133240000000)
  - (AAPL, CurrentRatio, 0.922938)
  - (AAPL, EBITMargin, 31.510223)
  - (AAPL, EBIT_Assets, 35.809756)
  - (AAPL, EBIT_Q, 42832000000)
  - (AAPL, EBIT_TTM, 123216000000)
  - (AAPL, EPS, 6.186841)
  - (AAPL, EV_EBIT, 29.347719)
  - (AAPL, EV_EBITDA, 26.853421)
  - (AAPL, GrossDebt, 96795000000)
  - (AAPL, GrossDebt_Equity, 1.449939)
  - (AAPL, GrossMargin, 46.20635)
  - (AAPL, NetDebt, 66496000000)
  - (AAPL, NetMargin, 23.971256)
  - (AAPL, NetProfit_Q, 36330000000)
  - (AAPL, NetProfit_TTM, 93736000000)
  - (AAPL, NetRevenue_Q, 124300000000)
  - (AAPL, NetRevenue_TTM, 391035000000)
  - (AAPL, P_B, 53.171343)
  - (AAPL, P_E, 38.145474)
  - (AAPL, P_EBIT, 29.018992)
  - (AAPL, PriceToAssets, 10.316092)
  - (AAPL, PriceToNetCurrentAssets, -319.066294)
  - (AAPL, PriceToSales, 9.143949)
  - (AAPL, PriceToWorkingCapital, -319.066294)
  - (AAPL, ROE, 140.411636)
  - (AAPL, ROIC, 75.337047)
  - (AAPL, ShareholdersEquity, 66758000000)
- AMZN: recommendation=Buy, target_price=256.03
  - recommendation_justification: Buy. Decisive indicators are the firm's strong capital efficiency and profitability — ROIC of 19.93% and trailing EPS of $5.53 — together with a net cash position of $20.63 billion that materially reduces balance‑sheet risk. A blended valuation using a 46x P/E and a 40x EV/EBIT produces a target price of $256.03, offering upside from the current $237.68 while acknowledging the stock's sensitivity to multiple compression.
  - (AMZN, AssetTurnover, 1.020908)
  - (AMZN, Assets, 624894000000)
  - (AMZN, BVPS, 26.673818)
  - (AMZN, CashAndEquivalents, 78779000000)
  - (AMZN, CurrentAssets, 190867000000)
  - (AMZN, CurrentRatio, 1.063735)
  - (AMZN, EBITMargin, 10.751945)
  - (AMZN, EBIT_Assets, 10.976742)
  - (AMZN, EBIT_Q, 21203000000)
  - (AMZN, EBIT_TTM, 68593000000)
  - (AMZN, EPS, 5.52635)
  - (AMZN, EV_EBIT, 36.848356)
  - (AMZN, EV_EBITDA, 24.902356)
  - (AMZN, GrossDebt, 58151000000)
  - (AMZN, GrossDebt_Equity, 0.203347)
  - (AMZN, GrossMargin, 48.854393)
  - (AMZN, NetDebt, -20628000000)
  - (AMZN, NetMargin, 9.287117)
  - (AMZN, NetProfit_Q, 9380000000)
  - (AMZN, NetProfit_TTM, 59248000000)
  - (AMZN, NetRevenue_Q, 187792000000)
  - (AMZN, NetRevenue_TTM, 637959000000)
  - (AMZN, P_B, 8.91061)
  - (AMZN, P_E, 43.008494)
  - (AMZN, P_EBIT, 37.149086)
  - (AMZN, PriceToAssets, 4.077759)
  - (AMZN, PriceToNetCurrentAssets, 222.819804)
  - (AMZN, PriceToSales, 3.994249)
  - (AMZN, PriceToWorkingCapital, 222.819804)
  - (AMZN, ROE, 20.718257)
  - (AMZN, ROIC, 19.932814)
  - (AMZN, ShareholdersEquity, 285970000000)
- COIN: recommendation=Hold, target_price=291.33
  - recommendation_justification: Hold. Elevated valuation metrics (P/E ≈30.7; P/S ≈12.1) are offset by robust profitability (TTM net margin ≈39.5%) and a net‑cash position of roughly $3.94 billion, while scenario analysis produces a wide range of outcomes (~$190–$380). The base‑case blended valuation aligns with the current share price, so a neutral stance is appropriate pending clearer volume recovery or regulatory clarity.
  - (COIN, AssetTurnover, 0.291192)
  - (COIN, Assets, 22541951000)
  - (COIN, BVPS, 37.592197)
  - (COIN, CashAndEquivalents, 8543903000)
  - (COIN, CurrentAssets, 18112653000)
  - (COIN, CurrentRatio, 2.280811)
  - (COIN, EBITMargin, 35.14854)
  - (COIN, EBIT_Assets, 10.234961)
  - (COIN, EBIT_Q, 1034069000)
  - (COIN, EBIT_TTM, 2307160000)
  - (COIN, EPS, 9.478661)
  - (COIN, EV_EBIT, 32.814095)
  - (COIN, EV_EBITDA, 31.095433)
  - (COIN, GrossDebt, 4608349000)
  - (COIN, GrossDebt_Equity, 0.448421)
  - (COIN, GrossMargin, 100)
  - (COIN, NetDebt, -3935554000)
  - (COIN, NetMargin, 39.476492)
  - (COIN, NetProfit_Q, 1294299000)
  - (COIN, NetProfit_TTM, 2591248000)
  - (COIN, NetRevenue_Q, 2271637000)
  - (COIN, NetRevenue_TTM, 6564028000)
  - (COIN, P_B, 7.749747)
  - (COIN, P_E, 30.735353)
  - (COIN, P_EBIT, 34.519895)
  - (COIN, PriceToAssets, 3.533098)
  - (COIN, PriceToNetCurrentAssets, 7.830136)
  - (COIN, PriceToSales, 12.133239)
  - (COIN, PriceToWorkingCapital, 7.830136)
  - (COIN, ROE, 25.214438)
  - (COIN, ROIC, 15.4997)
  - (COIN, ShareholdersEquity, 10276842000)
- GOOG: recommendation=Buy, target_price=208.703864
  - recommendation_justification: Buy. The recommendation rests on superior profitability (ROIC 33.12%, net margin 28.60%), a net-cash balance sheet (-$9.17B) and durable free cash flow that justify a premium multiple; blended P/E and EV/EBIT scenarios produce a target of $208.70 (~1.5% upside). Given modest near-term upside, this is a quality overweight predicated on continued ad and cloud execution; material regulatory or cyclical setbacks would prompt reassessment.
  - (GOOG, AssetTurnover, 0.777376)
  - (GOOG, Assets, 450256000000)
  - (GOOG, BVPS, 26.117458)
  - (GOOG, CashAndEquivalents, 23466000000)
  - (GOOG, CurrentAssets, 163711000000)
  - (GOOG, CurrentRatio, 1.836931)
  - (GOOG, EBITMargin, 32.109777)
  - (GOOG, EBIT_Assets, 24.961355)
  - (GOOG, EBIT_Q, 30972000000)
  - (GOOG, EBIT_TTM, 112390000000)
  - (GOOG, EPS, 8.043545)
  - (GOOG, EV_EBIT, 22.256567)
  - (GOOG, EV_EBITDA, 19.588066)
  - (GOOG, GrossDebt, 14300000000)
  - (GOOG, GrossDebt_Equity, 0.043989)
  - (GOOG, GrossMargin, 58.200435)
  - (GOOG, NetDebt, -9166000000)
  - (GOOG, NetMargin, 28.603672)
  - (GOOG, NetProfit_Q, 26536000000)
  - (GOOG, NetProfit_TTM, 100118000000)
  - (GOOG, NetRevenue_Q, 96469000000)
  - (GOOG, NetRevenue_TTM, 350018000000)
  - (GOOG, P_B, 7.72287)
  - (GOOG, P_E, 25.56087)
  - (GOOG, P_EBIT, 22.338123)
  - (GOOG, PriceToAssets, 5.575898)
  - (GOOG, PriceToNetCurrentAssets, 33.658872)
  - (GOOG, PriceToSales, 7.172721)
  - (GOOG, PriceToWorkingCapital, 33.658872)
  - (GOOG, ROE, 30.797578)
  - (GOOG, ROIC, 33.115881)
  - (GOOG, ShareholdersEquity, 325084000000)
- MSFT: recommendation=Sell, target_price=328.37
  - recommendation_justification: Sell. The decisive indicators are stretched market multiples — P/E 63.56 and EV/EBIT 50.36 — versus returns that, while strong (ROIC 17.63%, net margin 36.07%), do not by themselves justify further multiple expansion. Base‑case valuation scenarios (P/E = 50 and EV/EBIT = 40) imply a combined fair value near $328 per share, implying roughly 20% downside from the current $415.06, so the prudent action is to trim exposure and realize gains until valuation normalizes or performance meaningfully accelerates.
  - (MSFT, AssetTurnover, 0.253264)
  - (MSFT, Assets, 533898000000)
  - (MSFT, BVPS, 40.526844)
  - (MSFT, CashAndEquivalents, 17482000000)
  - (MSFT, CurrentAssets, 147080000000)
  - (MSFT, CurrentRatio, 1.35082)
  - (MSFT, EBITMargin, 46.003831)
  - (MSFT, EBIT_Assets, 11.651102)
  - (MSFT, EBIT_Q, 31653000000)
  - (MSFT, EBIT_TTM, 62205000000)
  - (MSFT, EPS, 6.530325)
  - (MSFT, EV_EBIT, 50.362819)
  - (MSFT, EV_EBITDA, 41.712524)
  - (MSFT, GrossDebt, 50218000000)
  - (MSFT, GrossDebt_Equity, 0.165903)
  - (MSFT, GrossMargin, 69.014251)
  - (MSFT, NetDebt, 32736000000)
  - (MSFT, NetMargin, 36.071648)
  - (MSFT, NetProfit_Q, 24108000000)
  - (MSFT, NetProfit_TTM, 48775000000)
  - (MSFT, NetRevenue_Q, 69632000000)
  - (MSFT, NetRevenue_TTM, 135217000000)
  - (MSFT, P_B, 10.241607)
  - (MSFT, P_E, 63.558855)
  - (MSFT, P_EBIT, 49.836559)
  - (MSFT, PriceToAssets, 5.806508)
  - (MSFT, PriceToNetCurrentAssets, 81.158258)
  - (MSFT, PriceToSales, 22.926726)
  - (MSFT, PriceToWorkingCapital, 81.158258)
  - (MSFT, ROE, 16.11358)
  - (MSFT, ROIC, 17.626157)
  - (MSFT, ShareholdersEquity, 302695000000)
- NFLX: recommendation=Buy, target_price=155.53
  - recommendation_justification: Netflix’s valuation is materially depressed (P/E ~4.93; EV/EBIT ~4.87) despite high profitability (ROIC 25.83% and net margin 22.34%) and manageable net leverage (net debt $7.78bn). A blended valuation using a P/E re‑rating to 8x and an EV/EBIT re‑rating to 7x yields a target of $155.53, implying meaningful upside and supporting a Buy.
  - (NFLX, AssetTurnover, 0.727218)
  - (NFLX, Assets, 53630374000)
  - (NFLX, BVPS, 56.329988)
  - (NFLX, CashAndEquivalents, 7804733000)
  - (NFLX, CurrentAssets, 13100379000)
  - (NFLX, CurrentRatio, 1.218028)
  - (NFLX, EBITMargin, 26.711169)
  - (NFLX, EBIT_Assets, 19.424839)
  - (NFLX, EBIT_Q, 2272766000)
  - (NFLX, EBIT_TTM, 10417614000)
  - (NFLX, EPS, 19.832471)
  - (NFLX, EV_EBIT, 4.865326)
  - (NFLX, EV_EBITDA, 4.716415)
  - (NFLX, GrossDebt, 15582804000)
  - (NFLX, GrossDebt_Equity, 0.629772)
  - (NFLX, GrossMargin, 46.056557)
  - (NFLX, NetDebt, 7778071000)
  - (NFLX, NetMargin, 22.336962)
  - (NFLX, NetProfit_Q, 1868607000)
  - (NFLX, NetProfit_TTM, 8711631000)
  - (NFLX, NetRevenue_Q, 10246513000)
  - (NFLX, NetRevenue_TTM, 39000966000)
  - (NFLX, P_B, 1.734067)
  - (NFLX, P_E, 4.925256)
  - (NFLX, P_EBIT, 4.118699)
  - (NFLX, PriceToAssets, 0.800051)
  - (NFLX, PriceToNetCurrentAssets, 18.297398)
  - (NFLX, PriceToSales, 1.100153)
  - (NFLX, PriceToWorkingCapital, 18.297398)
  - (NFLX, ROE, 35.20766)
  - (NFLX, ROIC, 25.833254)
  - (NFLX, ShareholdersEquity, 24743567000)
- NIO: recommendation=Hold, target_price=4.42
  - recommendation_justification: HOLD. The decisive indicators are a Price/Sales near 0.99 and implied market cap of ~$8.88B versus a TTM net loss of $3.104B and EPS of -$1.51, which argue against an immediate buy. Offsetting that, last quarter produced positive EBIT of $194.18M and the company carries a modest net debt balance (~$169.74M), indicating operational traction but not yet durable profitability. On balance, a cautious hold is warranted while we wait for multiple consecutive profitable quarters; our valuation work yields a conservative target of $4.42 that is roughly in line with the current price.
  - (NIO, AssetTurnover, 0.610862)
  - (NIO, Assets, 14741772000)
  - (NIO, BVPS, 0.900601)
  - (NIO, CashAndEquivalents, 2648051000)
  - (NIO, CurrentAssets, 8478354000)
  - (NIO, CurrentRatio, 0.99318)
  - (NIO, EBITMargin, -33.277876)
  - (NIO, EBIT_Assets, -20.328187)
  - (NIO, EBIT_Q, 194181000)
  - (NIO, EBIT_TTM, -2996735000)
  - (NIO, EPS, -1.510789)
  - (NIO, EV_EBIT, -3.018512)
  - (NIO, EV_EBITDA, -4.127065)
  - (NIO, GrossDebt, 2817795953.036592)
  - (NIO, GrossDebt_Equity, 1.522814)
  - (NIO, GrossMargin, 9.877696)
  - (NIO, NetDebt, 169744953.036592)
  - (NIO, NetMargin, -34.470023)
  - (NIO, NetProfit_Q, -125602000)
  - (NIO, NetProfit_TTM, -3104090000)
  - (NIO, NetRevenue_Q, 1171565000)
  - (NIO, NetRevenue_TTM, 9005187000)
  - (NIO, P_B, 4.796797)
  - (NIO, P_E, -2.859432)
  - (NIO, P_EBIT, -2.961868)
  - (NIO, PriceToAssets, 0.602094)
  - (NIO, PriceToNetCurrentAssets, -152.449843)
  - (NIO, PriceToSales, 0.985647)
  - (NIO, PriceToWorkingCapital, -152.449843)
  - (NIO, ROE, -167.753466)
  - (NIO, ROIC, -64.194878)
  - (NIO, ShareholdersEquity, 1850388000)
- TSLA: recommendation=Sell, target_price=54.21
  - recommendation_justification: Tesla's market multiples are the decisive indicators: a P/E near 200 and EV/EBIT near 199 stand in stark contrast to trailing profitability (TTM net margin ~7.26% and EPS ~$2.03). Conservative valuation scenarios (P/E 25 and EV/EBIT 25) produce a blended fair value near $54.21 per share versus the current $404.60, implying substantial downside if growth or margin expansion disappoints. Given the imbalance between valuation and demonstrated fundamentals, I recommend selling to reduce exposure to valuation compression.
  - (TSLA, AssetTurnover, 0.800279)
  - (TSLA, Assets, 122070000000)
  - (TSLA, BVPS, 21.063465)
  - (TSLA, CashAndEquivalents, 16139000000)
  - (TSLA, CurrentAssets, 58360000000)
  - (TSLA, CurrentRatio, 2.024912)
  - (TSLA, EBITMargin, 7.243321)
  - (TSLA, EBIT_Assets, 5.796674)
  - (TSLA, EBIT_Q, 1583000000)
  - (TSLA, EBIT_TTM, 7076000000)
  - (TSLA, EPS, 2.027158)
  - (TSLA, EV_EBIT, 198.845365)
  - (TSLA, EV_EBITDA, 125.672544)
  - (TSLA, GrossDebt, 7878000000)
  - (TSLA, GrossDebt_Equity, 0.106922)
  - (TSLA, GrossMargin, 17.862627)
  - (TSLA, NetDebt, -8261000000)
  - (TSLA, NetMargin, 7.258675)
  - (TSLA, NetProfit_Q, 2317000000)
  - (TSLA, NetProfit_TTM, 7091000000)
  - (TSLA, NetRevenue_Q, 25707000000)
  - (TSLA, NetRevenue_TTM, 97690000000)
  - (TSLA, P_B, 19.208616)
  - (TSLA, P_E, 199.589733)
  - (TSLA, P_EBIT, 200.012832)
  - (TSLA, PriceToAssets, 11.594092)
  - (TSLA, PriceToNetCurrentAssets, 47.912617)
  - (TSLA, PriceToSales, 14.487571)
  - (TSLA, PriceToWorkingCapital, 47.912617)
  - (TSLA, ROE, 9.62405)
  - (TSLA, ROIC, 8.676034)
  - (TSLA, ShareholdersEquity, 73680000000)

In [8]:
facts_df = pd.DataFrame(sample["data_input"], columns=["subject", "relation", "object"])
facts_df

               subject               relation       object
0    M_SMRG_2025-01-31         analysis_month   2025-01-31
1    M_SMRG_2025-01-31            stock_count            8
2    M_SMRG_2025-01-31          covers_ticker         AAPL
3                 AAPL         Recommendation         Hold
4                 AAPL            TargetPrice          236
..                 ...                    ...          ...
285               TSLA           PriceToSales    14.487571
286               TSLA  PriceToWorkingCapital    47.912617
287               TSLA                    ROE      9.62405
288               TSLA                   ROIC     8.676034
289               TSLA     ShareholdersEquity  73680000000

[290 rows x 3 columns]

In [9]:
stocks_df = pd.DataFrame(
    [
        {
            "ticker": row["ticker"],
            "recommendation": row["recommendation"],
            "target_price": row["target_price"],
            "recommendation_justification": row["recommendation_justification"],
            "indicator_count": len(row.get("indicators", {})),
        }
        for row in sample.get("stocks", [])
    ]
)
stocks_df

,ticker,recommendation,target_price,recommendation_justification,indicator_count
0,AAPL,Hold,236,I recommend Hold. The decisive indicators are ...,32
1,AMZN,Buy,256.03,Buy. Decisive indicators are the firm's strong...,32
2,COIN,Hold,291.33,Hold. Elevated valuation metrics (P/E ≈30.7; P...,32
3,GOOG,Buy,208.703864,Buy. The recommendation rests on superior prof...,32
4,MSFT,Sell,328.37,Sell. The decisive indicators are stretched ma...,32
5,NFLX,Buy,155.53,Netflix’s valuation is materially depressed (P...,32
6,NIO,Hold,4.42,HOLD. The decisive indicators are a Price/Sale...,32
7,TSLA,Sell,54.21,Tesla's market multiples are the decisive indi...,32

In [10]:
SELECTED_TICKER = sample["stocks"][0]["ticker"] if sample.get("stocks") else None

if SELECTED_TICKER is None:
    print("No stock rows available in this sample.")
else:
    stock_row = next(row for row in sample["stocks"] if row["ticker"] == SELECTED_TICKER)
    display(pd.Series({
        "ticker": stock_row["ticker"],
        "recommendation": stock_row["recommendation"],
        "target_price": stock_row["target_price"],
        "recommendation_justification": stock_row["recommendation_justification"],
        "indicator_count": len(stock_row.get("indicators", {})),
    }))

    indicators_df = pd.DataFrame(
        [
            {"indicator": key, "value": value}
            for key, value in sorted(stock_row.get("indicators", {}).items())
        ]
    )
    display(indicators_df)

ticker                                                                       AAPL
recommendation                                                               Hold
target_price                                                                  236
recommendation_justification    I recommend Hold. The decisive indicators are ...
indicator_count                                                                32
dtype: object

                  indicator         value
0             AssetTurnover      1.136449
1                    Assets  344085000000
2                      BVPS      4.406217
3        CashAndEquivalents   30299000000
4             CurrentAssets  133240000000
5              CurrentRatio      0.922938
6                EBITMargin     31.510223
7               EBIT_Assets     35.809756
8                    EBIT_Q   42832000000
9                  EBIT_TTM  123216000000
10                      EPS      6.186841
11                  EV_EBIT     29.347719
12                EV_EBITDA     26.853421
13                GrossDebt   96795000000
14         GrossDebt_Equity      1.449939
15              GrossMargin      46.20635
16                  NetDebt   66496000000
17                NetMargin     23.971256
18              NetProfit_Q   36330000000
19            NetProfit_TTM   93736000000
20             NetRevenue_Q  124300000000
21           NetRevenue_TTM  391035000000
22                      P_B     53.171343
23                      P_E     38.145474
24                   P_EBIT     29.018992
25            PriceToAssets     10.316092
26  PriceToNetCurrentAssets   -319.066294
27             PriceToSales      9.143949
28    PriceToWorkingCapital   -319.066294
29                      ROE    140.411636
30                     ROIC     75.337047
31       ShareholdersEquity   66758000000

In [11]:
selected_month = str(sample.get("analysis_date", ""))[:10]
month_outputs = sorted(DATASET_PATH.rglob(f"*_{selected_month}_output_*.json"))
month_manager = sorted(DATASET_PATH.rglob(f"*_{selected_month}_manager_decision_*.json"))

max_len = max(len(month_outputs), len(month_manager), 1)
artifact_table = pd.DataFrame(
    {
        "output_files": [
            str(month_outputs[i].relative_to(PROJECT_ROOT)) if i < len(month_outputs) else None
            for i in range(max_len)
        ],
        "manager_decision_files": [
            str(month_manager[i].relative_to(PROJECT_ROOT)) if i < len(month_manager) else None
            for i in range(max_len)
        ],
    }
)
artifact_table

,output_files,manager_decision_files
0,results/final_report2025_us/gpt-5/workflow_Fal...,results/final_report2025_us/gpt-5/workflow_Fal...
1,results/final_report2025_us/gpt-5/workflow_Tru...,results/final_report2025_us/gpt-5/workflow_Tru...
2,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
3,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
4,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
5,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
6,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
7,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
8,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
9,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
10,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
11,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
12,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
13,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
14,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
15,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
16,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...
17,results/final_report2025_us/gpt-5-mini/workflo...,results/final_report2025_us/gpt-5-mini/workflo...

In [12]:
display(Markdown("## Raw Selected Sample JSON"))
display(JSON(sample, expanded=False))

## Raw Selected Sample JSON